# Generated by Django 5.1.2 on 2024-11-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_clientes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
